services:
  haejoong-server-gateway:
    build: .
    container_name: haejoong-server-gateway
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - haejoong.com-network
      - courtcheck-network

networks:
  haejoong.com-network:
    external: true
  courtcheck-network:
    external: true
