log_format haejoong_server_gateway_log
    '$http_x_forwarded_for - $remote_user [$time_local] '
    '"$request" $status $body_bytes_sent '
    '"$http_referer" "$http_user_agent" '
    'host="$host" '
    'rt=$request_time '
    'urt="$upstream_response_time"';

# Docker embedded DNS
resolver 127.0.0.11 ipv6=off valid=10s;

# 해중.com
server {
    listen 3000;
    server_name 
        xn--955bn0u.com
        *.xn--955bn0u.com;
    
    server_tokens off;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    access_log /var/log/nginx/access.log haejoong_server_gateway_log;
    error_log /var/log/nginx/error.log warn;

    location / {
        set $upstream_api http://haejoong.com-api:3000;
        proxy_pass $upstream_api;
    }
}

# 코트체크.com
server {
    listen 3000;
    server_name
        xn--vx6b11cbyaf1e.com 코트체크.com
        *.xn--vx6b11cbyaf1e.com 코트체크.com;

    server_tokens off;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location / {
        set $upstream_api http://courtcheck-be:8080;
        proxy_pass $upstream_api;
    }
}
